In [1]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [2]:
data_raw=pd.read_csv('./trip_history.csv')
data = data_raw.copy()
data.head()

Duration  Start station number  End station number Bike number Member type
0      1012                 31208               31108      W00742      Member
1        61                 31209               31209      W00032      Member
2      2690                 31600               31100      W00993      Member
3      1406                 31600               31602      W00344      Member
4      1413                 31100               31201      W00883      Member

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115597 entries, 0 to 115596
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype 
---  ------                --------------   ----- 
 0   Duration              115597 non-null  int64 
 1   Start station number  115597 non-null  int64 
 2   End station number    115597 non-null  int64 
 3   Bike number           115597 non-null  object
 4   Member type           115597 non-null  object
dtypes: int64(3), object(2)
memory usage: 4.4+ MB


In [4]:
data.dtypes

Duration                 int64
Start station number     int64
End station number       int64
Bike number             object
Member type             object
dtype: object

In [5]:
data.head()

Duration  Start station number  End station number Bike number Member type
0      1012                 31208               31108      W00742      Member
1        61                 31209               31209      W00032      Member
2      2690                 31600               31100      W00993      Member
3      1406                 31600               31602      W00344      Member
4      1413                 31100               31201      W00883      Member

In [6]:
le=LabelEncoder()
le.fit(data['Member type'])
data['Member type']=le.transform(data['Member type'])

In [7]:
le=LabelEncoder()
le.fit(data['Bike number'])
data['Bike number']=le.transform(data['Bike number'])

In [8]:
data

Duration  Start station number  End station number  Bike number  \
0           1012                 31208               31108          608   
1             61                 31209               31209           35   
2           2690                 31600               31100          830   
3           1406                 31600               31602          276   
4           1413                 31100               31201          728   
...          ...                   ...                 ...          ...   
115592      2179                 31110               31623          710   
115593       953                 31106               31401          758   
115594       737                 31602               31401          813   
115595       514                 31111               31202          940   
115596     51962                 31111               31111          630   

        Member type  
0                 1  
1                 1  
2                 1  
3                 1  
4                 1  
...             ...  
115592            0  
115593            1  
115594            1  
115595            1  
115596            0  

[115597 rows x 5 columns]

In [9]:
data.shape

(115597, 5)

In [10]:
train=np.array(data.iloc[8:85000])
test=np.array(data.iloc[85000:,])

In [11]:
train.shape,test.shape

((84992, 5), (30597, 5))

In [12]:
from sklearn.naive_bayes import GaussianNB

In [13]:
model=GaussianNB()

In [14]:
model.fit(train[:,0:4],train[:,4])

GaussianNB()

In [15]:
predicted=model.predict(test[:,0:4])

In [16]:
test[:,4]

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)

In [17]:
predicted

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)

In [18]:
predicted.shape

(30597,)

In [19]:
count=0
for l in range(30597):
  if(predicted[l]== test[1,4]):
    count = count+1;

In [20]:
count

30126

In [21]:
print(count/30597)

0.9846063339543093


In [22]:
x= data.iloc[:,[0,1,2,3,4]].values
y= data.iloc[:, -1].values

In [23]:
x

array([[ 1012, 31208, 31108,   608,     1],
       [   61, 31209, 31209,    35,     1],
       [ 2690, 31600, 31100,   830,     1],
       ...,
       [  737, 31602, 31401,   813,     1],
       [  514, 31111, 31202,   940,     1],
       [51962, 31111, 31111,   630,     0]], dtype=int64)

In [24]:
y

array([1, 1, 1, ..., 1, 1, 0])

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.25, random_state= 0)

In [26]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy',min_samples_leaf= 4, random_state=0)
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=4, random_state=0)

In [27]:
y_test

array([1, 1, 1, ..., 1, 1, 1])

In [28]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [29]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
print(cm)

[[ 6089     0]
 [    0 22811]]


In [30]:
from sklearn import metrics
print("Accuracy",metrics.accuracy_score(y_test, y_pred))

Accuracy 1.0
